services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s
    networks:
      - scraper-net

  chrome:
    image: seleniarm/node-chromium:latest
    container_name: chrome
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2gb
    networks:
      - scraper-net

  gradireland-scraper:
    build: .
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - GRID_URL=http://selenium-hub:4444/wd/hub
    volumes:
      - ./data:/app/data
    command: ["python", "gradireland_scraper.py"]
    networks:
      - scraper-net

  model-trainer:
    build: .
    depends_on:
      - gradireland-scraper
    volumes:
      - ./data:/app/data
    command: ["python", "train_model.py"]
    networks:
      - scraper-net

  scraper:
    build: .
    depends_on:
      - model-trainer
    environment:
      - GRID_URL=http://selenium-hub:4444/wd/hub
    command: ["python", "scraper.py"]
    networks:
      - scraper-net

networks:
  scraper-net:
    driver: bridge
